#+Title: Intinerário formativo de Computação

Este repositório se destina a consolidar as aulas ministradas no Colégio Elite para o intinerário formativo de Computação.

* Objetivo
Este curso objetiva transmitir os conceitos básicos de Ciência da Computação para alunos no Ensino Médio, sem pressupor educação formal anterior na área.
* Forma de avaliação
Os alunos serão avaliados de duas formas:

** Laboratórios de programação
Para conteúdos práticos de programação, será esperado que o aluno faça a submissão de alguns projetos pertinentes ao assunto visto em sala de aula na plataforma [[https://www.beecrowd.com.br][repl.it]]. Tais exercícios são compostos de um enúnciado explicando o problema, alguns casos testes com suas entradas e repectivas saídas esperadas. Grande parte destes será inspirado na plataforma [[https://www.beecrowd.com.br][beecrowd.]]

Após correção automática na plataforma, o professor irá fazer a correção manual da qualidade do código. Cada exercício terá nota definida da seguinte forma:
- A nota inicial do aluno será proporcional a quantidade de testes automáticos que ele passou.
- Será deduzido da nota, após avaliação manual pelo professor, pontos por más práticas de programação:
  - (-10%) nomes de variáveis irrelevantes ou ambíguos ("var1", "auxaux1", etc).
  - (-20%) falta de documentação do código.
  - (-10%) repetição desnecessária de código.
  - (-50%) forjar a resposta correta com objetivo de fraudar os testes automáticos.

O aluno possui o prazo de 7 dias a partir da divulgação das notas para entrar em contato com o professor para questionar as deduções manuais.

** Questionários teóricos
Para conteúdos teóricos discutidos em sala de aula, será esperado que o aluno responda um questionário disponibilizado pelo professor via Google Forms.

** Prazos e dúvidas
O prazo de realização das atividades será de uma semana e é esperado que o aluno dedique em média uma hora para sua realização em casa.

Tendo em vista a natureza semanal do nosso curso, o professor se coloca disponível para tirar dúvidas referentes aos exercícios ou testes antes do horário de aula (14:00 - 14:30) e após (17:10 - 17:40) ás segundas-feiras ou por email (ieremies@gmail.com), este com o prazo de resposta de um dia útil.

Além disso, para os projetos na plataforma repl.it, há a possibilidade do aluno criar uma "Thread" selecionando a parte relevante do código e marcando "@ieremies".

** Originalidade e plágio
É esperado que o aluno pesquise em outras fontes e discuta com seus colegas sobre a disciplina e atividades. Contudo, as atividades são individuais e não será permitido colaboração entre os alunos na resulução destas.

Para ficar mais clara a distinção, abaixo há uma lista, não extensiva, do que é ou não esperado dos alunos. Cada caso será discutido com a Cordenação.

*** Permitido
- Discutir diferentes formas de resolução de laboratórios.
- Discutir o assunto da disciplina com colegas.
- Ajudar colegas a acharem bugs.
- Encorporar fragmentos de códigos disponíveis online, desde que não constituam parte significativa da atividade e a fonte seja creditada por meio de comentários no código.
- Discussão e compatilhamento de pseudo-código ou diagramas sobre as atividades com colegas.
*** Não permitido
- Compartilhar seu código ou resolução de questões na íntegra com colegas.
- Usar código disponível em outros meios sem citar fontes.
- Solicitar diretamente a solução de problemas ou perguntas online ou para terceiros.

* Fontes e inspirações
O [[https://studio.code.org/courses?view=teacher][code.org]] propõe o curso [[https://code.org/educate/csp][CS Principles]] com o seguinte [[https://docs.google.com/document/d/1myJwrDyRlAjwVNDS3gs-3JaJNhogsGMt9Swo-bpySgE/preview][currículo]]. Além disso, ele lista [[https://code.org/educate/curriculum/3rd-party][outros]] recursos.

O [[https://edu.google.com/intl/ALL_br/][Google for Education]] disponibiliza algumas ferramentas interessantes, com currículos, planos de aula e ferramentar. Dentre estes, destaco [[https://csfirst.withgoogle.com/c/cs-first/en/curriculum.html][CS First]] e [[https://beinternetawesome.withgoogle.com/pt-br_br/][Seja Incrível Na Internet]].

Artigos no assunto:
[[https://dl-acm-org.ez88.periodicos.capes.gov.br/doi/10.1145/2899415.2925496][- Teaching High School Students Computational Thinking with Hands-on Activities]]

Outro recurso importante para instrutores é o site [[https://csteachers.org/][Computer Science Teachers Association]].

A ACM faz sua recomendação de currículo a nível de graduação no [[https://www.acm.org/binaries/content/assets/education/curricula-recommendations/cc2020.pdf][relatório]] enquanto que a SBC descreve as [[https://www.sbc.org.br/educacao/diretrizes-para-ensino-de-computacao-na-educacao-basica][diretrizes para ensino de Computação na Educação Básica]].

** Harvard
Este curso é fortemente inspirado no curso de [[https://cs50.harvard.edu/ap/2022/][CS50 AP]] e pelo [[https://cs50.harvard.edu/x/2022/][CS50x 2022]]. Para educadores, [[https://cs50.harvard.edu/x/2022/workshop/][CS50 Educator Workshop 2021 - CS50x 2022]] é uma boa fonte de conhecimento.

** College Board
A "College Board" traça um bom currículo para a disciplina pré-universitário em [[https://apcentral.collegeboard.org/courses/ap-computer-science-principles?course=ap-computer-science-principles][AP Computer Science Principles]] e para o curso mais avançado [[https://apcentral.collegeboard.org/courses/ap-computer-science-a?course=ap-computer-science-a][AP Computer Science A]].

*** [[https://apcentral.collegeboard.org/courses/ap-computer-science-principles/course-audit][Course Audit]]
[[https://apcentral.collegeboard.org/pdf/available-ap-daily-videos-ap-computer-science-principles.pdf?course=ap-computer-science-principles]]
*** [[https://apcentral.collegeboard.org/courses/ap-computer-science-principles/classroom-resources][Classroom Resources]]
Essa página cita diversos recursos úteis para professores como planos de aulas e currículos. Mais notavelmente, [[https://www.codetra.in/resources][CodeTrain]] segue o currículo proposto pelo College Board e oferece planos de um ou dois anos de curso.

Além disso, há [[https://www.codetra.in/workshops][workshops]] regularmente disponibilizados.

Este curso possui forte inspiração no plano de dois anos disponibilizado em [[https://docs.google.com/document/d/1pnFFm8i9CzrsXJWNoCwiu8OczdI5N0ZaYp9rTou53fU/edit?usp=sharing][CodeTrain Resources - Sumary Doc]].
* Cronograma
O curso é planejado para dois anos. No primeiro ano, será apresentado introdução a linguagem de programação (como Python) e às suas estruturas mais comúns. O segundo ano será dedicado a aprofundar em conceitos de algoritmos e estruturas de dados, bem como POO.

O curso será divido em bimestres, cada bimestre com aproximadamente 10 aulas de 50 minutos.
** 1.1 - Introdução ao ambiente de programação e conceitos iniciais de processamento
[[https://docs.google.com/document/d/1yTNqWUgiZx1KLVRyQQOxdxpo82MHbw0VGMOiiUffrhw/edit#bookmark=id.tr9kxlmivusa][Year 1 - Unit 1b]]
** 1.2 - Condicionais, lógica booleana e funções
[[https://docs.google.com/document/d/1yTNqWUgiZx1KLVRyQQOxdxpo82MHbw0VGMOiiUffrhw/edit#bookmark=id.s5660bp34nut][Year 1- Unit 4]]
** 1.3 - A internet e webdesign
HTML, CSS e terminologia de rede.
[[https://docs.google.com/document/d/1yTNqWUgiZx1KLVRyQQOxdxpo82MHbw0VGMOiiUffrhw/edit#bookmark=id.jkoqbqkwz5xd][Year 1 - Unit 3]]
** 1.4 - Ética computacional
[[https://docs.google.com/document/d/1yTNqWUgiZx1KLVRyQQOxdxpo82MHbw0VGMOiiUffrhw/edit#bookmark=id.191317va9beh][Year 1 - Unit 0]]
[[https://docs.google.com/document/d/1yTNqWUgiZx1KLVRyQQOxdxpo82MHbw0VGMOiiUffrhw/edit#bookmark=id.b352z4kmtbsz][Year 1 - Unit 1 (parte final)]]
** 2.1 - Circuitos lógicos e arquitetura de computadores
[[https://docs.google.com/document/d/1yTNqWUgiZx1KLVRyQQOxdxpo82MHbw0VGMOiiUffrhw/edit#bookmark=id.uyyqt34z28md][Year 1 - Unit 2]]
** 2.2 - Algorítmos
[[https://docs.google.com/document/d/1kfmS2boiui3CSaT0jV7PlFaCPHcSvApcLIxiQUEFMXQ/edit#bookmark=id.lwj32yofv13h][Year 2 - Unit 1]]
** 2.3 - Estrutura de dados e programação orientada a objetos
[[https://docs.google.com/document/d/1kfmS2boiui3CSaT0jV7PlFaCPHcSvApcLIxiQUEFMXQ/edit#bookmark=id.6mr0r789vdca][Year 2 - Unit 4]]
** 2.4 - Java
